name: Tests

on:
  workflow_call:
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PNPM_CONFIG_FROZEN_LOCKFILE: false
    strategy:
      fail-fast: false
      matrix:
        firebase_admin: ['12', '13']
    name: tests (firebase-admin@${{ matrix.firebase_admin }})
    steps:
      - uses: actions/checkout@v6
      - name: cache firebase emulator
        uses: actions/cache@v5
        with:
          path: .cache/firebase
          key: ${{ runner.os }}-firebase-emulator

      - name: setup pnpm
        uses: valian-ca/github-workflows/.github/actions/setup-pnpm@main
      - name: Install firebase-admin@^${{ matrix.firebase_admin }}
        run: pnpm add -Dw firebase-admin@^${{ matrix.firebase_admin }}
      - name: dedupe
        run: pnpm dedupe
      - name: Set up Java for firebase emulators
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: '21'
      - name: tests
        run: pnpm test
